.github/workflows/ci.yml
.gitignore
.pre-commit-config.yaml
README.md
flake.lock
flake.nix

This PR adds:
- `flake-utils` for cross platform compatibility
- `pre-commit-hooks.nix` for formatting and linting
- `github actions ci` - A minimal CI config to make things easier when we want to build this out
- slight updates to the `README.md`

QOL Flakes Improvements

---

flake.lock
flake.nix
gm/default.nix
sconfig/default.nix
stoml/default.nix

closes https://github.com/informalsystems/cosmos.nix/issues/20

Package Gaia Manager

---

flake.lock
flake.nix

Closes https://github.com/informalsystems/cosmos.nix/issues/18
I investigated packaging tendermint rs again in this pr, but i don't think there are any executables in that either? I think it is just a collection of rust libraries. Let me know and I will close this as well https://github.com/informalsystems/cosmos.nix/issues/7

Switch rust packaging to use naersk

---

flake.lock
flake.nix
thor/default.nix
thor/go-modules.toml
thor/last-synced.narHash

Part of https://github.com/informalsystems/cosmos.nix/issues/19
There are 3 executables this provides:
- `thord`
- `thorcli`
- `bifrost`

Package Thor

---

flake.lock
syncGoModules/syncGoModules.hs

I found an error with my boolean monoids

Fix Sync Go Modules

---

flake.lock
flake.nix
regen/default.nix
regen/go-modules.toml
regen/last-synced.narHash

Package Regen

---

resources/gaia4/default.nix
resources/gaia5/default.nix
resources/gaia6/default.nix

Add ldflags to gaia

---

flake.lock
flake.nix
resources.nix
resources/gaia/default.nix

I switched rust package builder for hermes, and upgraded a bunch of stuff.

switch to buildRustPackage

---

checks.nix
flake.lock
flake.nix
modules/chains/gaia.nix
modules/relayer/hermes-toml.nix
modules/relayer/hermes.nix
modules/tests/gaia-test.nix
modules/tests/hermes-test.nix
resources.nix
resources/gaia/default.nix
resources/gm/default.nix
resources/goModParser.nix
resources/ibc-go/default.nix
resources/ts-relayer/default.nix
resources/utilities.nix
tests.nix

Depends on #70 going in first.

Switch formatter to alejandra

---

checks.nix
flake.lock
flake.nix
modules/chains/gaia.nix
modules/relayer/hermes-toml.nix
modules/relayer/hermes.nix
modules/tests/gaia-test.nix
modules/tests/hermes-test.nix
resources.nix
resources/gaia/default.nix
resources/gm/default.nix
resources/goModParser.nix
resources/ibc-go/default.nix
resources/ts-relayer/default.nix
resources/utilities.nix
tests.nix

Had to re-do cause it was branched off the other PR (the go deps refactor)

Switch formatter

---

flake.lock
flake.nix
resources.nix
resources/gaia/default.nix
resources/utilities.nix
scripts/default.nix
scripts/format.sh

Update to official release Gaia v7.0.0.

Update Gaia v7

---

.github/workflows/ci.yml
flake.lock
flake.nix
resources.nix
resources/apalache.nix

This PR adds [Apalache](https://github.com/informalsystems/apalache) to Cosmos.nix, using [`sbt-derivation`](https://github.com/zaninime/sbt-derivation) to build the Scala dependencies.

Add Apalache to Cosmos.nix

---

flake.lock
flake.nix
resources.nix

Add Interchain Security v1.0.4

---

checks.nix
flake.lock
flake.nix
resources.nix
resources/ibc-go/default.nix
resources/utilities.nix
scripts/default.nix
scripts/format.sh

This is based on that last commit from `master`, as there is no pre-release tagged yet.

Add ibc-go v7.0.0-pre.0

---

flake.lock
flake.nix
resources/gaia/default.nix

Update Gaia `v8.0.0-rc3` to `v8.0.1` and dd Gaia `v9.0.1`

Update Gaia v8.0.0-rc3 to v8.0.1 and add Gaia v9.0.1

---

flake.lock
flake.nix
resources.nix
resources/utilities.nix

Closes: #132
Additionally, this PR fixes the `wasmdPreFixupPhase` script to work on macOS as well.

Add `wasmd_next` at v0.40.0-rc.1

---

flake.lock
flake.nix
resources.nix
resources/utilities.nix

Update Hermes to v1.6.0 and add Centauri chain, GEX and `cosmwasm-check` tool

---

flake.lock
flake.nix
resources.nix

This PR adds Stride `v12.1.0` which is a consumer chain

Add Stride v12.1.0 which is a consumer chain

---

flake.nix
resources.nix

Add Stride no-admin for v12.1.0

Add stride no admin for v12.1.0

---

flake.lock
flake.nix
resources/gaia/default.nix

Add Gaia v12.0.0

---

flake.lock
flake.nix
resources.nix

This PR add the Celestia chain

Add Celestia chain

---

flake.lock
flake.nix
resources/gaia/default.nix

This PR adds two Gaia verisions:
* v13.0.2
* v14.0.0

Add Gaia v13 and v14

---

flake.lock
flake.nix
resources.nix

This PR adds Provenance Blockchain at version `v1.17.0`

Add Provenance Blockchain

---

flake.lock
flake.nix

next time i guess we will be able to make version releases

chore: start using centauri official repo as source

---

.github/workflows/ci.yml
.github/workflows/deploy.yaml
README.md

Setup S3 Cache

---

flake.nix

This feature is documented here:
- https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-format
- https://github.com/NixOS/nix/pull/4189

Include cache settings in flake

---

flake.lock
lib/default.nix
packages/crescent.nix
packages/ignite-cli.nix
packages/sifchain.nix
packages/simd.nix

`ldflags` is a list now in nixpkgs-unstable: https://github.com/NixOS/nixpkgs/blob/891a6348766ff17e4666b43aa94a28390467340e/pkgs/build-support/go/module.nix#L42

change ldflags and additionalLdFlags type to list

---

.github/workflows/ci.yml
.github/workflows/deploy.yaml
modules/apps.nix
modules/packages.nix
packages/beaker.nix
packages/hermes.nix
packages/namada.nix

This will enable us to populate the cache with mac artifacts, so that our apple inclined friends can benefit from binary distribution

Add CI support for Mac

---

flake.lock
flake.nix
modules/apps.nix
modules/packages.nix
packages/slinky.nix

Add Slinky

---

flake.lock
flake.nix
lib/default.nix
modules/nixosModules.nix
nixosModules/hermes/base.nix

Based on https://github.com/chessai/nix-std/commit/31bbc925750cc9d8f828fe55cee1a2bd985e0c00 upstream

Update nix-std to get toTOML that omits nulls

---

flake.lock
flake.nix
modules/apps.nix
packages/gaia.nix

__15.04.2024__
This PR adds Gaia `v15.2.0` which is the latest in https://cosmos.directory/cosmoshub/chain

Add Gaia `v15.2.0`

---

flake.lock
flake.nix
modules/apps.nix
packages/gaia.nix

__10.06.2024__
This PR adds Gaia `v17.2.0` as `#gaia17` taken from latest https://github.com/cosmos/gaia/releases

Add Gaia v17.2.0

---

flake.lock
flake.nix
modules/packages.nix
packages/libwasmvm.nix
packages/provenance.nix

This PR also adds `libwasmvm v2.1.0`

Update Provenance from v1.17.0 to v1.19.1

---

flake.lock
flake.nix
modules/packages.nix
packages/libwasmvm.nix
packages/wasmd.nix

Update `wasmd` from `v0.52.0` to `v0.53.0`

Update `wasmd` to `v0.53.0`

---

.github/workflows/ci.yml
flake.lock
flake.nix
packages/osmosis.nix

Update Osmosis from `v27.0.1` to `v28.0.0`

Update Osmosis from `v28.0.0`

---

flake.lock
flake.nix

fix: use git source for osmosis

---

flake.lock
flake.nix
modules/packages.nix
packages/gaia.nix
packages/libwasmvm.nix

This PR adds:
* Gaia `v23.3.0`
* libwasmvm `v2.2.3`

Add Gaia `v23.3.0`
