informalsystems/cosmos.nix

- .github/workflows/ci.yml
- .gitignore
- README.md
- flake.lock
- gm/default.nix
Closes https://github.com/informalsystems/cosmos.nix/issues/2
Closes https://github.com/informalsystems/cosmos.nix/issues/3
At some point I would like to provide a secret to this repo called `COSMOS_CACHE_KEY`. I don't have access to do this yet. It should be fine, since github actions are running on my fork as well, and therefore the cache should get pushed on every PR I make.
> Add Cosmos Cache

- README.md
- flake.lock
- flake.nix
This PR adds a more robust `shellHook` so that developers can enter the nix shell remotely. A "remote shell" is what I am calling a shell that is entered without cloning the repo. I have added instructions in the README on this. This should make things _much_ more convenient for developers who don't want to futz with nix or this repo (note: they will still have to install nix on their machine).
> Add Remote Shell

- README.md
- flake.nix
The official instruction for [installing Nix Flakes](https://nixos.wiki/wiki/Flakes) has been updated to:
```bash
nix-env -iA nixpkgs.nixFlakes
```
> Update instruction for installing Nix Flakes

- flake.lock
- flake.nix
- resources/apalache.nix
Use `make dist` instead of `sbt apalacheCurrentPackage` for building the package, as `apalacheCurrentPackage` does not fully install the package with all its dependencies.
Also updates Apalache version from `v0.23.1` to `v0.24.0`.
> Improve Apalache build steps

- flake.lock
- flake.nix
- resources/gaia/default.nix
- resources/ibc-go/default.nix
- tests.nix
- Update `gaia7` to `v7.0.1`
- Update `ibc-go-ics29-simapp` to `ibc-go-main-simapp`, as ICS29 has been merged into the `main` branch but not yet released.
- Remove the subversions `gaia6_0_2` to `gaia6_0_4`, and keep only `gaia6`, as the critical bugs in Gaia v6 has been resolved in v6.0.4.
> Update Gaia and ibc-go-simapp

- flake.lock
- flake.nix
- resources/ibc-go/default.nix
- resources/utilities.nix
This PR adds back the `ibc-go-ics29-simapp` that tracks the [beta branch for ICS29](https://github.com/cosmos/ibc-go/tree/ics29-beta2) for ibc-go. There is no need to merge this to `main`, as ICS29 has not been officially released.
This also updates the main branch for `ibc-go-main-simapp`.
> Add back `ibc-go-ics29-simapp`

- flake.lock
- flake.nix
- resources.nix
- resources/gaia/default.nix
- resources/ibc-go/default.nix
- resources/utilities.nix
Updated the following packages:
- `gaia7` to `v7.0.3`
- `ibc-go-v2-simapp` to `v2.3.1`
- `ibc-go-v3-simapp` to `v3.1.1`
- `ibc-go-v4-simapp` to `v4.0.0-rc2`
- `cosmos-sdk` to `v0.46.0`
Also added:
- `ibc-go-v5-simapp` at `v5.0.0-beta1`
> Update core Cosmos packages

- flake.lock
- flake.nix
- resources/gaia/default.nix
- resources/ibc-go/default.nix
The build of gaiad is failing, but I haven't been able to figure out how to fix it.
```
❯ nix shell '.#gaia8' 2>&1
this derivation will be built:
/nix/store/96dm64dssdbxa75f1989qcvvj0hpg1c8-gaia-v8.0.0-rc.drv
building '/nix/store/96dm64dssdbxa75f1989qcvvj0hpg1c8-gaia-v8.0.0-rc.drv'...
error: builder for '/nix/store/96dm64dssdbxa75f1989qcvvj0hpg1c8-gaia-v8.0.0-rc.drv' failed with exit code 1;
last 10 log lines:
> unpacking source archive /nix/store/ldambiicxmar8rsaapkq1i8vxrrplwam-source
> source root is source
> patching sources
> updateAutotoolsGnuConfigScriptsPhase
> configuring
> building
> Building subPackage ./ante
> go: -mod may only be set to readonly when in workspace mode, but it is set to "vendor"
>  Remove the -mod flag to use the default readonly value,
>        or set …
```
> Add Gaia v8.0.0-rc

- flake.lock
- flake.nix
- patches/stride-no-admin-check.patch
- resources.nix
This PR updates the version of Stride to `v5.1.1` and adds a `#stride-no-admin` which doesn't have the `ValidateAdminAddress `
The patched Stride is required to run Hermes' ICS31 tests, https://github.com/informalsystems/hermes/pull/3061. More specifically it allows any account to call the CLI `strided tx stakeibc register-host-zone`.
Without the patch, Stride will return an invalid creator address error when a non-admin account is used to register a host zone.
Registering a host zone is required in order to have Stride trigger Cross Chain Queries.
> Update Stride to v5.1.1 and add a patched Stride

- resources/ibc-go/default.nix
Ibc-go `simd` released `v7.0.0-rc1` which replaced Tendermint with CometBFT `v0.37`, https://github.com/cosmos/ibc-go/releases/tag/v7.0.0-rc1.
> Update simd to `v7.0.0-rc1`

- flake.lock
- flake.nix
- resources.nix
Update Osmosis from `v14.0.0` to `v15.0.0` as it is the version currently being used, see https://cosmos.directory/osmosis/chain
> Update Osmosis from v14.0.0 to v15.0.0

- flake.lock
- flake.nix
- patches/stride-no-admin-check.patch
- resources.nix
- resources/gaia/default.nix
This PR updates the following chains:
* Evmos from `v6.0.2` to `v9.1.0`
* Gaia from `v9.0.1` to `v9.0.3`
* Stride from `v7.0.0` to `v8.0.0`
* ~Juno from `v13.0.1` to `v14.1.0`~
* Juno requires some additional tweaks and will be updated in a separate PR
> Update Evmos, Gaia and Stride chains

- resources.nix
This PR aims to fix the following error while building cosmos/relayer via "nix build .#relayer" command.
$ nix build .#relayer
error: hash mismatch in fixed-output derivation '/nix/store/cvrqsrvk6vik2r5k65yzrmskzv3mhx00-relayer-go-modules.drv':
specified: sha256-AelUjtgI9Oua++5TL/MEAAOgxZVxhOW2vEEhNdH3aBk=
got:    sha256-oJSxRUKXhjpDWk0bk7Q8r0AAc7UOhEOLj+SgsZsnzsk=
error: 1 dependencies of derivation '/nix/store/xz50gfl88xin3ziaynpnjrkp9hnybcpn-relayer.drv' failed to build
> Update vendorSha256 for cosmos/relayer in resources.nix file

- flake.lock
- flake.nix
- resources/ibc-go/default.nix
This PR updates ibc-go simapp from `v8.0.0-beta.1` to the release `v8.0.0`
> Update ibc-go v8.0.0

- flake.lock
- flake.nix
- resources.nix
This PR updates the following chain versions:
* Osmosis from `v19.2.0` to `v20.4.0`
* Neutron from `v1.0.2` to `v1.0.4`
* Migaloo from `v2.0.2` to `v3.0.2`
* Osmosis from `v1.0.1` to `v1.0.4`
> Update multiple chain versions

- flake.lock
- flake.nix
- packages/ibc-go.nix
This PR update the tag used for simapp channel upgrade from alpha to rc.0
> Update channel upgrade tag from alpha to rc.0

- flake.lock
- flake.nix
- packages/ibc-go.nix
This PR updates ibc-go v8 simapp from v8.0.0 to v8.1.0
Since the v8.1.0 has the channel upgrade feature, it also removes the `ibc-go-v8-channel-upgrade-simapp`
> Update simapp from v8.0.0 to v8.1.0

- flake.lock
- flake.nix
- modules/apps.nix
- modules/packages.nix
- packages/celestia-app.nix
- packages/celestia-node.nix
This adds the `celestia-node` package, i.e. celestia's Data Availability node (as opposed to the already included `celestia` package which is actually `celestia-app`, the consensus node).
This also changes the name of the existing `celestia` package to `celestia-app` to better match the documentation and its `celestia-appd` binary, and to reduce confusion around the `celestia` binary which is actually included with the `celestia-node` package.
A wrapper `celestia` package has been included that wraps the `celestia-app` and `celestia-node` packages under a single `celestia` package using `symlinkJoin`. As a result, building `celestia` now produces the same binaries that it used to (`celestia-appd`) while also providing the actual `celestia` binary from the `celestia-node` package.
Here's …
> celestia-node: init at v0.13.0, rename old `celestia` to `celestia-app`, add `celestia` combined pkg

- flake.lock
- flake.nix
- modules/packages.nix
- packages/rollapp-evm.nix
Currently fails with
```
❯ nix shell '.#rollapp-evm'
error: builder for '/nix/store/lgm1ayp1m9hhxpjvmjsicv7gri7n854a-rollapp-evm-v2.0.0-beta-7-g21b29f6-go-modules.drv' failed with exit code 1;
last 10 log lines:
> go: downloading github.com/go-logr/logr v1.2.4
> go: downloading github.com/google/pprof v0.0.0-20230817174616-7a8ec2ada47b
> go: downloading github.com/google/s2a-go v0.1.7
> go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.2
> go: downloading github.com/go-logr/stdr v1.2.2
> go: downloading github.com/polydawn/refmt v0.0.0-20201211092308-30ac6d18308e
> go: downloading github.com/ghodss/yaml v1.0.0
> go: downloading github.com/blang/semver v3.5.1+incompatible
> go: updates to go.mod needed; to update it:
>   go mod tidy
For full logs, run 'nix log …
```
> Add Rollapp EVM

- flake.lock
- flake.nix
- packages/ibc-go.nix
This PR updates the ibc-go versions:
* ibc-go `v4.2.0` -> `v4.6.0`
* ibc-go `v5.1.0` -> `v5.4.0`
* ibc-go `v6.1.0` -> `v6.3.0`
* ibc-go `v7.3.0` -> `v7.4.0`
* ibc-go `v8.1.0` -> `8.2.0`
> Update ibc-go versions

- flake.lock
- flake.nix
- packages/osmosis.nix
__15.04.2024__
This PR updates Osmosis from v22.0.5 to v24.0.1 which is the latest in https://cosmos.directory/osmosis/chain
> Update Osmosis version from v22 to v24 

- flake.lock
- flake.nix
- modules/apps.nix
- modules/packages.nix
- packages/neutron.nix
- packages/stride.nix
- patches/stride-no-admin-check.patch
This PR does the following:
* Remove Stride before it was a Consumer chain, Stride v8
* Update Stride Consumer chain from v12.1.0 to v21.0.0
* Update Neutron Consumer chain from v2.0.0 to v3.0.2
> Update Consumer chains

- flake.lock
- flake.nix
- modules/packages.nix
- packages/juno.nix
__19.04.2024__
This PR updates Juno from version `v17.1.1` to `v21.0.0` which is the latest on https://cosmos.directory/juno/chain
> Update Juno to version `v21.0.0`

- flake.lock
- flake.nix
- modules/packages.nix
- packages/migaloo.nix
__19.04.2024__
This PR updates Migaloo Chain from version v3.0.2 to v4.1.3 which is the latest on https://cosmos.directory/migaloo/chain
> Update Migaloo Chain to version v4.1.3

- flake.lock
- flake.nix
- packages/ibc-go.nix
This PR updates the ibc-go simapp `v8.2.0` to `v8.3.1`
> Update ibc-go simapp from `v8.2.0` to `v8.3.1`

- flake.lock
- flake.nix
- packages/osmosis.nix
__10.06.2024__
Update Osmosis version from v24.0.1 to v25.0.0, version tagged as latest in https://github.com/osmosis-labs/osmosis/releases
> Update Osmosis version

- flake.lock
- flake.nix
- packages/neutron.nix
Update Neutron from v3.0.2 to v3.0.5, version tagged as latest in https://github.com/neutron-org/neutron/releases
> Update Neutron version

- flake.lock
- flake.nix
- modules/packages.nix
- packages/libwasmvm.nix
- packages/wasmd.nix
__10.06.2024__
Update wasmd from v0.50.0 to v0.51.0, version tagged as latest in https://github.com/CosmWasm/wasmd/releases
This PR also adds libwasmvm v2.0.0
> Update wasmd from v0.50.0 to v0.51.0

- flake.lock
- flake.nix
- lib/default.nix
- modules/devshells.nix
- packages/andromeda.nix
- packages/apalache.nix
- packages/gaia.nix
- packages/ibc-go.nix
- packages/injective.nix
- packages/juno.nix
- packages/provenance.nix
- packages/rollapp-evm.nix
__10.06.2024__
Update Juno from v21.0.0 to v22.0.0, version tagged as latest in https://github.com/CosmosContracts/juno/releases.
This PR also updates nixpkgs to the latest, with `nix flake lock --update-input nixpkgs` in order to have access to go v1.22.3. This requires the removal of go v1.20 since the attribute `buildGo120Module` is now missing.
This PR also replaced `rnix-lsp` from `devshells.nix`, as it is unmaintained, with oxalica `nil` https://github.com/oxalica/nil/tree/2023-08-09.
This PR also updates Apalache from v0.42.0 to v0.44.11.
> Update Juno version

- flake.lock
- flake.nix
- packages/celestia-app.nix
This PR also updates nixpkgs to the latest, with `nix flake lock --update-input nixpkgs` in order to have access to go v1.22.4 or higher.
> Update Celestia app from `v1.11.0` to `v1.14.0`

- flake.lock
- modules/packages.nix
- packages/ibc-go.nix
This PR update building ibc-go v9 in order to build it with wasm enabled
> Build ibc-go v9 with wasm enabled

- flake.lock
- flake.nix
- modules/apps.nix
- modules/packages.nix
- packages/ibc-go.nix
This PR supersedes #220 and adds the latest Wasm variant of ibc-go v7 and v8:
- [modules/light-clients/08-wasm/v0.4.1+ibc-go-v8.4-wasmvm-v2.0](https://github.com/cosmos/ibc-go/releases/tag/modules%2Flight-clients%2F08-wasm%2Fv0.4.1%2Bibc-go-v8.4-wasmvm-v2.0)
- [modules/light-clients/08-wasm/v0.3.1+ibc-go-v7.4-wasmvm-v1.5](https://github.com/cosmos/ibc-go/releases/tag/modules%2Flight-clients%2F08-wasm%2Fv0.3.1%2Bibc-go-v7.4-wasmvm-v1.5)
> Add Wasm variant of ibc-go v7 and v8

- flake.lock
- flake.nix
- packages/ibc-go.nix
Updates the following versions of ibc-go simapp:
* v6: from `v6.3.0` to `v6.3.1`
* v7: from `v7.4.0` to `v7.8.0`
* v8: from `v8.3.1` to `v8.5.1`
* v9: from `v9.0.0-beta.1` to `v9.0.0-rc.0`
> Update simapp minor versions

- flake.lock
- flake.nix
- modules/apps.nix
- modules/packages.nix
- packages/cometbft.nix
- packages/gaia.nix
- packages/interchain-security.nix
~Currently using latest commit of branch `main`.~ 
~This needs to be updated when the alpha tag for v20 is added to the Gaia repository~
__30.09.2024__
Updated with tag `v20.0.0`
__23.10.2024__
* Add Gaia `v20.0.0`
* Update CometBFT from `v0.38.0` to `v0.38.11`
* Update Interchain Security from `feat/ics-misbehaviour-handling` to `v6.1.0`
> Add Gaia v20

- flake.lock
- flake.nix
- modules/apps.nix
- modules/packages.nix
- packages/ibc-go.nix
- packages/libwasmvm.nix
This PR adds ibc-go `v9` with WASM client.
And adds libwasmvm `v2.1.4` as well.
This PR also removes the following from `apps.nix`:
* `gaia` as it was referencing `gaia6_0_3`
* `gaia4`
__Status 08.01.2025__
Since the tag `modules/light-clients/08-wasm` for `v9` was not found the branch `08-wasm/release/v0.5.x%2Bibc-go-v9.0.x-wasmvm-v2.1.x` has been used instead
> Add ibc-go-v9 with wasm
